# Generated by Django 5.1.2 on 2024-10-19 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.PositiveIntegerField()),
                ('base_ac', models.PositiveIntegerField()),
                ('mana', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('inventory', models.ManyToManyField(related_name='+', to='rpg.items')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rpg.jobs')),
            ],
        ),
    ]
