# Generated by Django 5.1.2 on 2024-10-19 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_HP', models.PositiveIntegerField()),
                ('base_AC', models.PositiveIntegerField()),
                ('mana', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rpg.job'),
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
